name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тегов вида v1.0, v2.1.3 и т.д.

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build library
        run: cmake --build build --target matrix

      - name: Prepare release files
        run: |
          mkdir -p release
          cp src/matrix.h release
          cp build/libmatrix.a release
          cd release
          tar -czf ../matrix-${{ github.ref_name }}.tar.gz *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: matrix-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}